/*
 * File: app/model/Department.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.model.Department', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Rest',
        'Ext.data.field.String'
    ],


    proxy: {
        type: 'rest',
        url: '/data/department/'
    },
    fields: [
        {
            type: 'string',
            mapping: 'DEPT_NO',
            name: 'id'
        },
        {
            mapping: 'DEPARTMENT',
            name: 'department'
        }
    ]

});