/*
 * File: app/model/Job.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.model.Job', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Number',
        'Ext.data.proxy.Rest'
    ],


    fields: [
        {
            mapping: 'JOB_CODE',
            name: 'jobCode'
        },
        {
            type: 'int',
            mapping: 'JOB_GRADE',
            name: 'jobGrade'
        },
        {
            mapping: 'JOB_COUNTRY',
            name: 'jobCountry'
        },
        {
            mapping: 'JOB_TITLE',
            name: 'jobTitle'
        },
        {
            type: 'float',
            mapping: 'MIN_SALARY',
            name: 'minSalary'
        },
        {
            type: 'float',
            mapping: 'MAX_SALARY',
            name: 'maxSalary'
        },
        {
            mapping: 'JOB_REQUIREMENT',
            name: 'jobRequirement'
        }
    ],
    proxy: {
        type: 'rest',
        url: '/data/job/'
    }

});