/*
 * File: app/view/EmployeeForm.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.view.EmployeeForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.employeeform',

    requires: [
        'EmployeeApp.view.EmployeeFormViewModel',
        'EmployeeApp.view.EmployeeFormViewController',
        'Ext.field.Date',
        'Ext.field.Number',
        'Ext.field.ComboBox',
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Toast'
    ],

    controller: 'employeeform',
    viewModel: {
        type: 'employeeform'
    },
    title: 'Employee Details',

    items: [
        {
            xtype: 'textfield',
            bind: '{employee.firstName}',
            label: 'First Name',
            required: true,
            maxLength: 15
        },
        {
            xtype: 'textfield',
            bind: '{employee.lastName}',
            label: 'Last Name',
            required: true,
            maxLength: 20
        },
        {
            xtype: 'datefield',
            bind: '{employee.hireDate}',
            label: 'Hire Date',
            required: true
        },
        {
            xtype: 'numberfield',
            bind: '{employee.phoneExt}',
            label: 'Extension',
            maxLength: 4
        },
        {
            xtype: 'combobox',
            label: 'Department',
            required: true,
            editable: false,
            displayField: 'department',
            store: 'Department',
            valueField: 'id',
            queryMode: 'local',
            bind: {
                value: '{employee.deptId}'
            }
        },
        {
            xtype: 'combobox',
            reference: 'countryCombo',
            label: 'Country',
            required: true,
            editable: false,
            displayField: 'value',
            queryMode: 'local',
            bind: {
                value: '{employee.jobCountry}',
                store: '{country}'
            },
            listeners: {
                change: 'onCountryChange'
            }
        },
        {
            xtype: 'combobox',
            reference: 'jobCodeCombo',
            label: 'Job Code',
            required: true,
            editable: false,
            displayField: 'value',
            queryMode: 'local',
            bind: {
                value: '{employee.jobCode}',
                store: '{jobcode}'
            },
            listeners: {
                change: 'onJobCodeChange'
            }
        },
        {
            xtype: 'combobox',
            reference: 'jobGradeCombo',
            label: 'Job Grade',
            required: true,
            editable: false,
            displayField: 'value',
            queryMode: 'local',
            bind: {
                value: '{employee.jobGrade}',
                store: '{jobgrade}'
            },
            listeners: {
                change: 'onJobGradeChange'
            }
        },
        {
            xtype: 'numberfield',
            reference: 'salaryField',
            label: 'Salary',
            required: true,
            maxValue: 999999999,
            minValue: 0,
            bind: {
                value: '{employee.salary}'
            }
        },
        {
            xtype: 'toolbar',
            docked: 'top',
            items: [
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-save',
                    text: 'Save',
                    listeners: {
                        tap: 'onSaveTap'
                    }
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-undo',
                    text: 'Cancel',
                    listeners: {
                        tap: 'onCancelTap'
                    }
                },
                {
                    xtype: 'spacer'
                },
                {
                    xtype: 'button',
                    iconCls: 'x-fa fa-trash',
                    text: 'Delete',
                    bind: {
                        hidden: '{employee.phantom}'
                    },
                    listeners: {
                        tap: 'onDeleteTap'
                    }
                }
            ]
        }
    ]

});