/*
 * File: app/view/EmployeeGridViewModel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.view.EmployeeGridViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.employeegrid',

    requires: [
        'Ext.data.Store',
        'Ext.util.Sorter'
    ],

    data: {
        employeeRecord: null
    },

    stores: {
        employee: {
            groupField: 'department',
            autoLoad: false,
            model: 'EmployeeApp.model.Employee',
            sorters: [
                {
                    property: 'firstName'
                },
                {
                    property: 'lastName'
                }
            ]
        },
        job: {
            autoLoad: false,
            model: 'EmployeeApp.model.Job',
            listeners: {
                load: 'onJobStoreLoad'
            }
        },
        country: {
            model: 'EmployeeApp.model.LookupItem',
            sorters: {
                property: 'value'
            }
        },
        jobcode: {
            model: 'EmployeeApp.model.LookupItem',
            sorters: {
                property: 'value'
            }
        },
        jobgrade: {
            model: 'EmployeeApp.model.LookupItem',
            sorters: {
                property: 'value'
            }
        }
    }

});