/*
 * File: app/view/LoginForm.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.view.LoginForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.loginform',

    requires: [
        'EmployeeApp.view.LoginFormViewModel',
        'EmployeeApp.view.LoginFormViewController',
        'Ext.field.Password',
        'Ext.field.Checkbox'
    ],

    controller: 'loginform',
    viewModel: {
        type: 'loginform'
    },
    keyMap: {
        Enter: 'onLoginTap'
    },
    keyMapEnabled: true,
    shadow: true,
    width: 350,
    bodyPadding: 12,
    buttons: [
        {
            text: 'Login',
            handler: 'onLoginTap'
        }
    ],
    title: 'Login',

    items: [
        {
            xtype: 'textfield',
            name: 'username',
            label: 'Login'
        },
        {
            xtype: 'passwordfield',
            name: 'password',
            label: 'Password'
        },
        {
            xtype: 'checkbox',
            reference: 'rememberMe',
            label: 'Remember Me?',
            checked: true
        }
    ]

});