/*
 * File: app/view/MainPanel.js
 *
 * This file was generated by Sencha Architect version 4.2.8.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 7.2.x Modern library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 7.2.x Modern. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EmployeeApp.view.MainPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.mainpanel',

    requires: [
        'EmployeeApp.view.MainPanelViewModel',
        'EmployeeApp.view.MainPanelViewController',
        'EmployeeApp.view.LoginForm',
        'EmployeeApp.view.EmployeeGrid',
        'Ext.Tool',
        'Ext.form.Panel',
        'Ext.grid.Grid'
    ],

    controller: 'mainpanel',
    viewModel: {
        type: 'mainpanel'
    },
    layout: 'card',
    title: 'Employee Directory',

    tools: [
        {
            xtype: 'tool',
            reference: 'logout',
            hidden: true,
            iconCls: 'x-fa fa-user-lock',
            listeners: {
                click: 'onLogoutClick'
            }
        }
    ],
    items: [
        {
            xtype: 'container',
            layout: 'center',
            items: [
                {
                    xtype: 'loginform'
                }
            ]
        },
        {
            xtype: 'employeegrid'
        }
    ],
    listeners: {
        initialize: 'onPanelInitialize'
    }

});